[workspace]

members = [
    "q-002",
    "q-004",
    "q-007",
    "q-010",
    "q-014",
    "q-016",
    "q-022",
    "q-024",
    "q-027",
    "q-033",
    "q-055",
    "q-061",
    "q-067",
    "q-078",
]
